<a href="https://colab.research.google.com/github/chakravartulavinay/UNP_ASSIGNMENT_2023/blob/main/UnpAssignment4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
# 1. Read the CSV file into a DataFrame and display the first 15 rows.
path = '/content/drive/MyDrive/Copy of weather_data.csv'
df=pd.read_csv(path)##reading the file
df.head(15)

,City,Condition,Temperature (C),Humidity (%),Wind Speed (km/h),Precipitation (mm)
0,Philadelphia,Cloudy,2.4,78,7.4,NaN
1,Chicago,Sunny,28.7,53,1.9,45.4
2,Chicago,Sunny,-5.4,74,9.3,NaN
3,Philadelphia,Rainy,0.8,63,25.0,8.3
4,Philadelphia,Cloudy,2.9,43,20.7,46.7
5,Chicago,Sunny,13.7,75,27.1,34.4
6,Phoenix,Rainy,11.0,39,13.5,20.7
7,Phoenix,Rainy,2.3,50,13.4,26.5
8,Phoenix,Rainy,NaN,93,11.8,14.1
9,Philadelphia,Snowy,17.9,78,9.7,NaN
10,New York,Rainy,31.1,49,8.7,49.7
11,Phoenix,Cloudy,36.0,77,1.8,13.5
12,Los Angeles,Sunny,-1.3,48,3.5,39.5
13,Philadelphia,Sunny,36.8,52,0.5,NaN
14,Houston,Snowy,NaN,65,10.9,23.2

In [3]:
# 2. Calculate the total number of rows and columns in the dataset.
df.shape

(1000, 6)

In [4]:
# 3. Identify and list the names of cities present in the dataset

#indentifying cities
Identifying_cities=df['City']

# coverting the indentified cities into set and than to list
cities_present=list(set(Identifying_cities))


print(f"The list of cities in the dataset are:{cities_present}")

The list of cities in the dataset are:['Chicago', 'Philadelphia', 'New York', 'Phoenix', 'Houston', 'Los Angeles']

In [5]:
# 4. Find the total number of missing values in each column.
missing_values=pd.isna(df).sum()
missing_values

City                   0
Condition              0
Temperature (C)       45
Humidity (%)           0
Wind Speed (km/h)      0
Precipitation (mm)    51
dtype: int64

In [6]:
# 5. Handle the missing values in the 'Temperature (C)' and 'Precipitation (mm)' columns. Replace NaN values with the mean of the respective columns.
mean_temp=df['Temperature (C)'].fillna(format(df['Temperature (C)'].mean(),'.1f'),inplace=True)
mean_prec=df['Precipitation (mm)'].fillna(format(df['Precipitation (mm)'].mean(),'.1f'),inplace=True)
df

,City,Condition,Temperature (C),Humidity (%),Wind Speed (km/h),Precipitation (mm)
0,Philadelphia,Cloudy,2.4,78,7.4,25.2
1,Chicago,Sunny,28.7,53,1.9,45.4
2,Chicago,Sunny,-5.4,74,9.3,25.2
3,Philadelphia,Rainy,0.8,63,25.0,8.3
4,Philadelphia,Cloudy,2.9,43,20.7,46.7
...,...,...,...,...,...,...
995,Phoenix,Rainy,17.4,40,4.9,23.7
996,Phoenix,Snowy,20.5,64,18.0,4.0
997,Chicago,Snowy,-7.4,46,29.4,45.9
998,Chicago,Rainy,-5.6,39,23.0,47.0
999,Philadelphia,Snowy,14.4,59,29.2,42.5

In [8]:
# 6. Calculate the average temperature for each city and display the result in descending order.
avg_temp = df.groupby('City').agg({'Temperature':'mean'}).sort_values('Temperature')
avg_temp ## it executed before but now I am getting an error

KeyError: ignored

In [9]:
 # 7. Find the city with the highest average humidity and display the city name and the average humidity value.
avg_humidity=df.groupby('City').agg({'Humidity (%)':'mean'}).sort_values('Humidity (%)')
avg_humidity_dataframe=pd.DataFrame(avg_humidity)
max_avg_humidity=avg_humidity_dataframe['Humidity (%)'].max()
result = avg_humidity_dataframe.loc[avg_humidity_dataframe['Humidity (%)']==max_avg_humidity]
result

              Humidity (%)
City
Philadelphia     61.867725

In [10]:
# 8. Create a new DataFrame that includes only the rows where the 'Condition' column is 'Rainy' and the 'Wind Speed (km/h)' is greater than 10.
rainy_days=df.loc[df['Condition']=='Rainy']
wind_speed=df.loc[df['Wind Speed (km/h)'] > 10]
d=pd.merge(rainy_days,wind_speed)
d

,City,Condition,Temperature (C),Humidity (%),Wind Speed (km/h),Precipitation (mm)
0,Philadelphia,Rainy,0.8,63,25.0,8.3
1,Phoenix,Rainy,11.0,39,13.5,20.7
2,Phoenix,Rainy,2.3,50,13.4,26.5
3,Phoenix,Rainy,14.4,93,11.8,14.1
4,Chicago,Rainy,-2.1,66,10.5,15.1
...,...,...,...,...,...,...
145,Houston,Rainy,38.4,74,28.7,3.5
146,Philadelphia,Rainy,26.0,27,18.5,43.2
147,Philadelphia,Rainy,15.4,56,17.4,8.7
148,Phoenix,Rainy,-2.3,35,19.7,13.2
149,Chicago,Rainy,-5.6,39,23.0,47.0

In [11]:
# 9. Calculate the percentage of rainy days with wind speed greater than 10 km/h.
d['percent']=(d['Wind Speed (km/h)']/d['Wind Speed (km/h)'].sum())*100
d
d.loc[:,['Condition','Wind Speed (km/h)','percent']]

    Condition  Wind Speed (km/h)   percent
0       Rainy               25.0  0.842914
1       Rainy               13.5  0.455174
2       Rainy               13.4  0.451802
3       Rainy               11.8  0.397856
4       Rainy               10.5  0.354024
..        ...                ...       ...
145     Rainy               28.7  0.967666
146     Rainy               18.5  0.623757
147     Rainy               17.4  0.586668
148     Rainy               19.7  0.664217
149     Rainy               23.0  0.775481

[150 rows x 3 columns]

In [12]:
# 10. Save the new DataFrame (from task 8) into a new CSV file named 'rainy_windy_days.csv
x=pd.DataFrame(d)
x.to_csv('rainy_windy_days.csv')